[package]
name = "polyai"
version = "0.1.0"
edition = "2024"

[dependencies]
autocxx = "0.30.0"
cxx = "1.0.173"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
debug = 0

[build-dependencies]
autocxx-build = "0.30.0"
